#!/usr/bin/env python3
"""
Derive each workflow's on-prem BPMN template from its Cloud + Edge template.

The two editions run the same process: every Data X-Ray call is a loop of
"script arms a request -> transport task runs it -> script handles the
response". They differ only in the transport task and the configuration
variables, so workflow.bpmn.template (on-prem) is GENERATED from
workflow.edge.bpmn.template, which is the one to edit:

  - every External API task (<serviceTask flowable:type="http">) becomes an
    async script task running {{script:dxr_call_direct.groovy}} (HTTPS with
    the Bearer token, shared/dxr_http_direct.groovy);
  - the Edge HTTP connection name and the links-only base URL become the
    required Data X-Ray base URL and Bearer token (sentinel defaults);
  - results per request defaults to 100 (no 100 KB response cap on-prem).

    python tools/derive_onprem_bpmn.py           # rewrite the on-prem templates
    python tools/derive_onprem_bpmn.py --check   # exit 1 if any is out of date
"""
import argparse
import re
import sys
from pathlib import Path

PACK = Path(__file__).resolve().parents[1]

ONPREM_CONFIG = (
    '{ind}<flowable:formProperty id="dataxrayUrl" name="Data X-Ray Base URL" type="string" variable="dataxrayUrl" '
    'default="&lt;paste Data X-Ray base URL here&gt;" readable="false" required="true"/>\n'
    '{ind}<flowable:formProperty id="dataxrayAuthToken" name="Data X-Ray Auth Token (Bearer)" type="string" '
    'variable="dataxrayAuthToken" default="&lt;paste Data X-Ray Bearer token here&gt;" readable="false" required="true"/>\n'
)

HEADER = """<!--
  GENERATED by tools/derive_onprem_bpmn.py from workflow.edge.bpmn.template: do not
  edit this file; edit the Edge template and re-run the tool.

  On-prem edition. Identical to the Cloud + Edge edition except that each Data
  X-Ray call ({tasks}) is an async script task
  that calls Data X-Ray over HTTPS with the admin's Bearer token, and the
  configuration variables are the Data X-Ray base URL, the Bearer token and the
  results page size. The flow is described in workflow.edge.bpmn.template.
-->"""


def derive(edge_text: str) -> str:
    out = edge_text

    tasks = []

    def to_script_task(m: re.Match) -> str:
        head = m.group(1)
        task_id = re.search(r'\bid="([^"]+)"', head).group(1)
        name = re.search(r'\bname="([^"]*)"', head).group(1).replace(' (Edge)', '')
        tasks.append(task_id)
        return (f'<scriptTask id="{task_id}" name="{name}" scriptFormat="groovy" flowable:async="true" '
                f'flowable:exclusive="true" flowable:autoStoreVariables="false">\n'
                f'      <extensionElements>\n'
                f'        <design:stencilid><![CDATA[ScriptTask]]></design:stencilid>\n'
                f'      </extensionElements>\n'
                f'      <script>{{{{script:dxr_call_direct.groovy}}}}</script>\n'
                f'    </scriptTask>')

    out, n_tasks = re.subn(r'<serviceTask\b([^>]*flowable:type="http"[^>]*)>.*?</serviceTask>',
                           to_script_task, out, flags=re.S)
    if n_tasks == 0:
        raise ValueError('no External API task found')

    out, n_conn = re.subn(r'^([ \t]*)<flowable:formProperty id="dataxrayConnectionName"[^\n]*\n',
                          lambda m: ONPREM_CONFIG.format(ind=m.group(1)), out, flags=re.M)
    if n_conn != 1:
        raise ValueError('expected one dataxrayConnectionName formProperty')
    out = re.sub(r'^[ \t]*<flowable:formProperty id="dataxrayUrl" name="Data X-Ray Base URL \(deep links only\)"[^\n]*\n',
                 '', out, flags=re.M)
    out = re.sub(r'(<flowable:formProperty id="dataxrayPageSize"[^>]*default=")25(")', r'\g<1>100\2', out)

    header = HEADER.format(tasks=', '.join(tasks))
    out, n_head = re.subn(r'<!--.*?-->', lambda m: header, out, count=1, flags=re.S)
    if n_head != 1:
        raise ValueError('expected a leading comment')
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--check', action='store_true', help='report stale templates instead of rewriting them')
    args = ap.parse_args()
    stale = []
    for edge in sorted(PACK.glob('workflows/*/workflow.edge.bpmn.template')):
        target = edge.with_name('workflow.bpmn.template')
        text = derive(edge.read_text(encoding='utf-8'))
        if target.exists() and target.read_text(encoding='utf-8') == text:
            continue
        stale.append(target.relative_to(PACK))
        if not args.check:
            target.write_text(text, encoding='utf-8')
    for p in stale:
        print(f"{'stale' if args.check else 'wrote'}: {p}")
    if args.check and stale:
        sys.exit(1)


if __name__ == '__main__':
    main()
